name: Deploy to Vercel (main only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Trigger Vercel Deploy Hook
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Deploy Hook
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"